### ISSUE TITLE
Missing Libraries after stack install

### ISSUE THREAD

**Issue by DwordPtr** [SmallImprovements/spring-clean#1]
Disclaimer: I know very little about haskell.
I wanted to try spring-clean out on a legacy app, isntalled stack from scratch  and let it install the compiler.

I'm getting an error message
````

    Process exited with code: ExitFailure 1
    Logs have been written to: /home/bryan/Dev_/spring-clean/.stack-work/logs/regex-pcre-0.94.4.log

    Configuring regex-pcre-0.94.4...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: Missing dependency on a foreign
    library:
    * Missing C library: pcre
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.

````
I don't know much about these or if stack can resolve these dependencies but I'd appreciate some guidance.

My os

````
Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS Release: 16.04 Codename: xenial
````

**Comment by DwordPtr** [comment]
Nevermind I managed to find the library in apt.

**Comment by petercrona** [comment]
Hi, 
Nice that you managed to solve it! Hope you find some unused code as well :)

**Comment by DwordPtr** [comment]
There's a lot haha. Although it's not strictly a spring mvc project. I've checked some random classes in the list and they look unused (at least to alt-f7). 

I'm thinking your code is more general than it seems.
